version: '3.8'

services:
  syntax_squad_server:
    image: nginx:alpine
    container_name: syntax_squad_server
    restart: unless-stopped
    tty: true
    ports:
      - "1002:1002"
    depends_on:
      - syntax_squad_database
      - syntax_squad_post_service
      - syntax_squad_chat_service
      - syntax_squad_auth_service
    volumes:
      - ./post-service:/var/www/post-service
      - ./.docker/nginx/conf/local:/etc/nginx/conf.d
      - ./.docker/nginx/log:/var/log/nginx
    networks:
      - network

  syntax_squad_auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: syntax_squad_auth_service
    restart: unless-stopped
    tty: true
    env_file:
      - ./auth-service/.env
    ports:
      - "2000:2000"
    volumes:
      - ./auth-service:/usr/src/app/syntax-squad/auth-service
      - ./auth-service/package.json:/usr/src/app/syntax-squad/auth-service/package.json
      - ./auth-service/package-lock.json:/usr/src/app/syntax-squad/auth-service/package-lock.json
      - /usr/src/app/syntax-squad/auth-service/node_modules
    networks:
      - network

  syntax_squad_chat_service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: syntax_squad_chat_service
    restart: unless-stopped
    tty: true
    env_file:
      - ./chat-service/.env
    ports:
      - "2001:2001"
    volumes:
      - ./chat-service:/usr/src/app/syntax-squad/chat-service
      - ./chat-service/package.json:/usr/src/app/syntax-squad/chat-service/package.json
      - ./chat-service/package-lock.json:/usr/src/app/syntax-squad/chat-service/package-lock.json
      - /usr/src/app/syntax-squad/chat-service/node_modules
    networks:
      - network

  syntax_squad_post_service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: syntax_squad_post_service
    restart: unless-stopped
    tty: true
    env_file:
      - ./post-service/.env
    ports:
      - "5001:5001"
    volumes:
      - ./post-service:/var/www/post-service
      - ./.docker/php/local.ini:/usr/local/etc/php/local.ini
    networks:
      - network

  syntax_squad_database:
    image: mysql:8
    container_name: syntax_squad_database
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env.database
    ports:
      - "3307:3307"
    expose:
      - 3307
    volumes:
      - database_volume:/var/lib/mysql/
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_volume: